version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest tests/
      - run:
          name: store test results
          command: mv pytest-results* ~/repo/logs/
      - store_artifacts:
          path: ~/repo/logs
          destination: Junit
      - store_test_results:
          path: ~/repo/logs
